### PR TITLE
Updating cosmos DB packages

### LINKED ISSUE #642: Update Cosmos DB packages
Had a CRI involving cosmos DB and output binding. Cosmos DB team recommended upgrading to the latest version since it had improvements around how connections are made among other things.

### PR DESCRIPTION
**Pull request by yojagad**
Fixes #642 as part of CRI.

### CODE REVIEW

**Comment by pragnagopa** [comment]
Please open an issue and link to the PR. Issue will help attach repair item to the CRI

**Comment by pragnagopa** [comment]
@brettsam  - Ok to release cosmos extension with this change? Also, can we ask customer to update  the nuget package themselves?

**Comment by brettsam** [comment]
@yojagad -- need to bump the Cosmos extension version here too. Should be 3.0.8.

**Comment by brettsam** [comment]
@ealsur -- FYI -- it was recommended (via an incident -- Pragna and Yogesh would have details) that we move these forward to latest. Just wanted to keep you aware :-)

**Comment by yojagad** [comment]
Bumped up the version

**Comment by brettsam** [comment]
3.0.8 was never published, was it? It doesn't look like it -- but I can publish it now.

**Comment by techfg** [comment]
@brettsam - Is does not appear that 3.0.8 was ever published.  Doing so would resolve the issue with #647.  Was there anything blocking 3.0.8 from being published?

**Comment by ealsur** [comment]
@techfg 3.0.8 was published https://www.nuget.org/packages/Microsoft.azure.webjobs.extensions.cosmosdb/3.0.8

**Comment by techfg** [comment]
Thank you for the quick attention to this @ealsur!

**Pull request merged**
