### PR TITLE
[Timer] improving verbose logs to help diagnostics

### PR DESCRIPTION
**Pull request by brettsam**

### CODE REVIEW

**Comment by fabiocav** [comment]
This is a pretty old PR. Still relevant?

**Comment by brettsam** [comment]
Yikes, I didn't realize this never went in. Yeah, we should get it in. I've just rebased it on dev.

**Comment by grahamehorner** [comment]
having looked at the code I think this may address my
https://github.com/Azure/azure-webjobs-sdk-extensions/issues/454 issue.

**Comment by grahamehorner** [comment]
could we add a line at the and of the output, something like ‘and the every 2hrs.” ...

**Comment by mathewc** [comment]
Is this PR in or can it be closed?

**Comment by grahamehorner** [comment]
@mathewc it looks to me that it's either not in or not working; as the output is still broken up with other lines of output text, making hard to determine which timer function/trigger will execute when.

**Comment by brettsam** [comment]
@mathewc -- Let's get it in. But I need an approval  :-)

**Comment by grahamehorner** [comment]
@brettsam FWIW you have my approval LOLZ :-)

**Comment by grahamehorner** [comment]
https://www.bing.com/images/search?view=detailV2&ccid=MF9rsW%2b2&id=54B7EF026E4E42FBA5F828BEEAF781C94F15FC01&thid=OIP.MF9rsW-2GjqE2gZ-i29OZgHaGR&mediaurl=https%3a%2f%2fshipitsquirrel.github.io%2fimages%2fsquirrel.png&exph=254&expw=300&q=ship+it+squirrel&simid=608033188321886954&selectedIndex=0&ajaxhist=0

**Comment by grahamehorner** [comment]
[https://www.bing.com/images/search?view=detailV2&ccid=MF9rsW%2b2&id=54B7EF026E4E42FBA5F828BEEAF781C94F15FC01&thid=OIP.MF9rsW-2GjqE2gZ-i29OZgHaGR&mediaurl=https%3a%2f%2fshipitsquirrel.github.io%2fimages%2fsquirrel.png&exph=254&expw=300&q=ship+it+squirrel&simid=608033188321886954&selectedIndex=0&ajaxhist=0
](url)

**Comment by grahamehorner** [comment]
squirrel

**Pull request merged**
