### PR TITLE
Update CosmosDB dependencies to latest versions for cross-partition offset/limit support

### PR DESCRIPTION
**Pull request by trbenning**
The current versions, Microsoft.Azure.DocumentDB.Core,2.3.0 & Microsoft.Azure.DocumentDB.ChangeFeedProcessor,2.2.6 do not support OFFSET LIMIT clauses on cross-partition queries, but the new versions do. This PR simply updates those packages.

### CODE REVIEW

**Comment by trbenning** [comment]
Resolves issue #621

**Comment by ealsur** [comment]
CFP does not really apply to the bindings, just bumping the SDK would do

**Comment by trbenning** [comment]
Fair enough. I'll back out the CFP change & update the PR later today.

**Comment by ealsur** [comment]
@brettsam I'm ok with this bump, it makes sense (for just the SDK). Only question would be, should the PR also bump the Extension version?

**Comment by fabiocav** [comment]
> @brettsam I'm ok with this bump, it makes sense (for just the SDK). Only question would be, should the PR also bump the Extension version?

Please. A minor bump for this would be needed.

**Comment by ealsur** [comment]
@trbenning Could you also bump the Cosmos DB Extension version?  https://github.com/Azure/azure-webjobs-sdk-extensions/blob/28023f6552cadf8bfbb86f9c135b49cf0a89b178/build/common.props#L6

**Comment by trbenning** [comment]
Will do

**Comment by anthonychu** [comment]
@ealsur Checking in on the progress. Seeing other folks asking for this to be addressed as well. https://github.com/Azure/azure-functions-core-tools/issues/1929

**Comment by ealsur** [comment]
@anthonychu I already signed off. The CI issues might need a Functions member to look into.

**Comment by ealsur** [comment]
Looks like one of the issues is on the `ExtensionsSample.csproj` project, with a different SDK version, might be that that project needs to be in sync. But there is another failure related to Storage, and this PR doesn't seem to be changing that, so not sure what's up with that.

**Comment by anthonychu** [comment]
@ealsur Thanks. I missed that. @brettsam could you please take a look?

**Comment by brettsam** [comment]
Ugh. It looks like there's a conflict now b/c we've moved our Storage references (which the core Extensions project uses) to newer packages, and now use Cosmos.Table. That package requires a narrow range of Cosomos packages which this now falls outside of.

```
ExtensionsSample -> Microsoft.Azure.WebJobs.Extensions.CosmosDB -> Microsoft.Azure.DocumentDB.Core (>= 2.9.2)  
ExtensionsSample -> Microsoft.Azure.WebJobs.Extensions.Storage 4.0.0-preview1 -> Microsoft.Azure.Cosmos.Table 1.0.5 -> Microsoft.Azure.DocumentDB.Core (>= 2.1.3 && <= 2.4.2).
```

This means you couldn't use our latest Storage extension side-by-side with the Cosmos extension anymore. It looks like they changed the dependency on Microsoft.Azure.Cosmos.Table 1.0.6 -- what if you add a direct nuget package reference to that in ExtensionsSample? Does that get it building?

**Comment by ealsur** [comment]
@trbenning Does the fix proposed (update the dependency on the ExtensionsSample.csproj) fix the CI issue? Do you get a similar error locally?

**Comment by trbenning** [comment]
Adding `<PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.6" />` to ExtensionsSample.csproj & WebJobs.Extensions.CosmosDB.Tests.csproj gets rid of the errors, but I can't vouch for whether or not that introduces any runtime issues. Do you want me to push that change?

**Comment by brettsam** [comment]
Go ahead and rebase with that change and lets see if the tests pass.

**Comment by trbenning** [comment]
@brettsam @ealsur, I've added the references, but several tests fail. They don't seem to be related to this fix though. There are a lot of failures due to missing configs, and what not. Did I miss something that would have caused that?

**Comment by ealsur** [comment]
The problem might be that `Microsoft.Azure.Cosmos.Table` 1.0.6 has an SDK dependency of >= 2.10.0.

So the `Microsoft.Azure.DocumentDB.Core` dependency might need to be `2.10.1` (latest).

Also @brettsam is there a way to re-trigger the CI? Some of those Test failures seem to be unrelated (like failures on HttpTrigger), and could be transient?

**Comment by brettsam** [comment]
It was missing the `full-ci` label. But it still looks like there are conflicts. Can you rebase this on the latest dev and take care of the conflicts then re-push?

**Comment by trbenning** [comment]
The PR is already synced up with origin/dev. I merged it in this commit: 1ef547265fc463a7d8eb5c7e7b270c65a45e3db1. I can back that out and rebase instead if you'd prefer though. The PR status is now showing no conflicts, and that all tests have passed, so are there any issues we still need to resolve?

**Comment by brettsam** [comment]
I'm seeing this -- do you not see this? 

image

**Comment by brettsam** [comment]
Oh, nevermind -- that's b/c i had "rebase" selected by default. Squash and merge will work. Sorry about that!

**Comment by trbenning** [comment]
No, this is all I see. I didn't realize that PR process required a rebase. I'll go ahead and replace the merge with a rebase.

image

**Comment by brettsam** [comment]
No you're okay (our comments crossed) -- I just saw that and assumed that there were merge conflicts. But it was b/c I had "Rebase and merge" selected by default. With "Squash and merge" it looks like it'll work fine.

**Comment by davidhousedev** [comment]
Would love to get an estimated time when this will go live! We're about to use a hacky approach that we wouldn't have to take if this fix is merged soon.

**Comment by brettsam** [comment]
We're currently having some issues with our release builds (signing-related) but hopefully we can get this out next week.

**Comment by probablyup** [comment]
@brettsam is there a public changefeed somewhere we can keep an eye on to know when this launches?

**Comment by brettsam** [comment]
It's out -- https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.CosmosDB/3.0.6

**Comment by probablyup** [comment]
Thanks @brettsam!

**Comment by probablyup** [comment]
@brettsam unfortunately it doesn't seem like it's working via https://github.com/Azure/azure-functions-core-tools. Can you comment?

**Comment by probablyup** [comment]
Ok I figured out that this package needed to be updated downstream: https://github.com/Azure/azure-functions-extension-bundles/pull/20

However there is an issue in that extension release in that it relies on https://www.nuget.org/packages/Microsoft.Azure.WebJobs 3.0.17 which doesn't appear to be released yet. I only see up to 3.0.16 on nuget

@brettsam

**Comment by brettsam** [comment]
Oh shoot -- yeah this dependency is a problem. Let me look at it. I think it worked for both @ealsur and I because this release was already in our staging myget feed.

**Comment by ealsur** [comment]
Yeah, I added MyGet as a feed and seems like VS pulled all dependencies from where it could. Thus pulling 3.0.17 from MyGet too.

**Comment by brettsam** [comment]
Unfortunately 3.0.17 isn't in prod yet so I can't just deploy that to nuget. I'm changing the dependency here to 3.0.16 (there's really no need for it to be bumped) and will re-deploy a 3.0.7 with the updated dependency. That PR is here -- https://github.com/Azure/azure-webjobs-sdk-extensions/pull/639

**Comment by brettsam** [comment]
3.0.7 is now out. Sorry about that!

**Comment by brettsam** [comment]
And yes -- for non-.NET we need to push this to the bundle release. @soninaren is working on that and he said he'd add 3.0.7 to the next bundle update.

**Pull request merged**
