### PR TITLE
Update SendGrid package to 9.10.0

### PR DESCRIPTION
**Pull request by burkeholland**
While putting together a project, I noticed that in order to use SendGrid's dynamic templates, you have to add a reference to the SendGrid 9.10.0 package into your Functions project ([sample repo here](https://github.com/burkeholland/serverless-sendgrid-report/blob/master/extensions.csproj)). 

Updating the dependency here should add support for dynamic templates (transactional templates).

### CODE REVIEW

**Comment by mathewc** [comment]
Let's do it

**Comment by brettsam** [comment]
Hmm, "full-ci" didn't seem to work. I'll investigate later today.

**Comment by ashi20007** [comment]
Hi Brett, Is there any update as to when we are planning to release Microsoft.Azure.WebJobs.Extensions.SendGrid library which will point to latest version of sendgrid such that Version 9.10.0.

There are various new features related to dynamic template like setTemplateData which is missing in current release Microsoft.Azure.WebJobs.Extensions.SendGrid -Version 3.0.0

**Comment by brettsam** [comment]
Tests went green here. Turns out it was just a failed call to Github when this originally ran, so no changes were required. I'm going to go ahead and merge this so we can get generated nuget packages. 

@burkeholland / @ashi20007, would either of you be able to take that package and run a simple test on it to make sure it unblocks you?

**Comment by brettsam** [comment]
FYI the new SendGrid package can be found here: https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-extensions/build/artifacts.

**Pull request merged**
