### PR TITLE
Catch all routes in proxies should not override /admin routes.

### PR DESCRIPTION
**Pull request by safihamid**
https://github.com/Azure/azure-functions-host/issues/2590

### CODE REVIEW

**Comment by paulbatum** [comment]
If I understand this change correctly does it really resolve Azure/azure-functions-host#2590 ? A catchall route would not start with the string "admin". Is this fix just handling the case where the user attempts to override admin through proxies, not using a catch-all?

**Comment by safihamid** [comment]
@paulbatum other than /admin endpoints we are fine and the user can do a catch-all for all other routes. This is the behavior we had in V1 as well, Am i Missing something?

**Comment by paulbatum** [comment]
So putting aside proxies for a second, here is an example of the case that I think @fabiocav was worried about when he filed that issue:

```csharp        
public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "{*test}")] HttpRequest req,
            ILogger log)
```

If you do this, then you'll override admin endpoints such as `/admin/host/status`. You can try this yourself locally very easily.

Extending this scenario to proxies, I suspect you should be worried about this case:

```javascript
{
    "proxies": {
        "proxy_test": {
            "debug": true,
            "matchCondition": {
                "route": "/{*test}"
            },
            "backendUri": "https://somehost.azurewebsites.net/admin/{test}"
        }
    }
}
```

**Comment by safihamid** [comment]
Thanks @paulbatum for the examples. Verified the function example works with this fix. and /admin endpoints can still be reached even with the Route specified above in function code and removing routePrefix.

For the proxy example, the example above was never supported even in V1. in V1 we were returning infinite loop detected and now with this fix we return 404 which is even better I think.

**Pull request merged**
